#
# $Id: GNUmakefile,v 1.2 2010/07/27
#
# jseldred@email.wm.edu
#
include SoftRelTools/arch_spec_root.mk
LIB_TYPE    := shared
LIB         := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)

########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_art.mk
